### ISSUE TITLE
Case problem with ruby 1.9

### ISSUE THREAD

**Issue by GaryPickrell** [texel/runt#1]
Running ruby 1.9 it reports

runt.rb:88: syntax error, unexpected tSTRING_BEG, expecting keyword_then or ',' or ';' or '\n' (SyntaxError)
      when 1 "#{number}st"

The solution is to change the case to strings.  

```
   case "#{number.to_i % 10}"
      when "1" "#{number}st"
      when "2" "#{number}nd"
      when "3" "#{number}rd"
```

**Comment by texel** [comment]
This isn't a canonical repo, and I"m not the maintainer of runt, but send me a pull request and I'll merge it in.

**Comment by pmarreck** [comment]
FYI to original reporter: I initiated a pull request and it's merged in. Now I just have to figure out how to tell Ruby to get and use the new version... lol

**Comment by pmarreck** [comment]
i.e., using the "gem install" command doesn't get this version. Do you have to push the updated code to a gem repo somewhere or something? (I haven't made any public gems yet)

**Comment by texel** [comment]
This isn't the official runt gem- that repo isn't on github and it's essentially been abandoned. If you're using bundler, you can use any git repo as a source. You can find more info here:
http://gembundler.com/git.html
